################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
#  productName: FirstVision - LATAM
#  whoIsItFor: LATAM
#  image: 
#    link: "/assets/images/Fiserv_Logo.jpg"
#    altText: FirstVision - LATAM™
  productionDescription: Expand your business’ reach by taking the acceptance process to a different level. SILVERCORE ™ is our processing solution that meets your challenges head-on and transforms your technology capability. We provide an end-to-end solution. SILVERCORE™ Restful APIs enable you to achieve platform modernization and competitive edge delivering the following benefits to your business. Banking Issuers, Financial Institutions can rely on Fiserv for innovative solutions and services that offer a wide range of functionalities, such as account and card processing, tokenization validations, digital wallets;  also payment services, risk and fraud management, data analysis, cardholder call center and other needs for the payments business.
getStarted: docs/getting-started.md
guides:
  - title: Introduction
    description: Introduction for Silvercore APIS.
    link: docs/1-introduction.md
benefits:
  - title: Time to Market
    description: Service-based architecture with API enabled and a fully integrated suite of solutions ensures quicker application development and integration.
    icon: assets/images/time.jpg
  - title: Transform Business
    description: Platform architecture built around technology simplification and leveraging open APIs, reducing the cost of change and meeting the innovation.
    icon: assets/images/transform1.png
  - title: Speed to Market
    description: SILVERCORE™ oriented architecture with open APIs enables service consumption rather than change management.
    icon: assets/images/transform.png
featuredFeatures:
  - title: Accounts
    description: We offer different inquiries via Restful that allows to show account information such as components (main account + additionals), financial status and online transactional activity. It also offer other satellite actions such as limit management, travel notification, card turn off, among others.
    featured: true
    relatedDocs:
    - link: docs/api-reference/1-account.md
      title: Accounts
    relatedAPIs:
    - title: Accound availability
      type: "post"
      path: "/accounts/availability"
  - title: Cards
    description: We provide APIs designed for credit and prepaid card management to support account/card sign-up,  lifecycle and other additional processing actions. Includes card level features such as card activation, issue, reissue, lost and stolen, replacement, Secured PIN management, card details, etc.
    featured: true
    relatedDocs:
    - link: docs/api-reference/2-cards.md 
      title: Cards
    relatedAPIs:
    - title: Instant Issuance
      type: "put"
      path: "/cards/instantIssuance"
